_wandb:
    value:
        cli_version: 0.19.1
        m:
            - "1": train_iou_class_3_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_iou_class_3_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_iou_class_1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_iou_class_4
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_iou_class_2
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_iou_class_0
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_iou_class_1_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_mean_iou_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_iou_class_4_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_iou_class_1_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_iou_class_0
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_iou_class_0_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_iou_class_4
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_iou_class_3
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_iou_class_2_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_mean_iou_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_iou_class_3
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_mean_iou
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_iou_class_4_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_iou_class_2
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_iou_class_1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_iou_class_0_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_iou_class_2_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_mean_iou
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 9
                - 41
                - 49
                - 55
                - 63
                - 74
                - 103
            "2":
                - 1
                - 9
                - 41
                - 49
                - 55
                - 63
                - 74
                - 103
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
learning_rate:
    value: 0.0001
num_classes:
    value: 5
